spring.application.name=Journal_management_system
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#logging.level.org.mongodb.driver=DEBUG
logging.level.com.basavaLearing.jornalApp=DEBUG
weather.api.key={key}
# email configuration...
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username={mail}
spring.mail.password={password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.data.redis.url={redis url}

# Expose all endpoints
management.endpoints.web.exposure.include=*

# Show details in health checks
management.endpoint.health.show-details=always

# Optional: run actuator on a different port
management.server.port=8081

# Application info for /actuator/info
info.app.name=Order Service
info.app.version=1.0.0
info.app.owner=Tech Team